config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :funerals, only: %i[show new create destroy update index] do
    resources :guests, only: %i[index new show create edit update destroy]
    resources :funeral_flowers, only: %i[index show new create edit update destroy]
    resources :venues, only: %i[index new show create edit update destroy]
    resources :funeral_homes, only: %i[index show new create edit update destroy]
    resources :relatives, only: %i[new show create]
    member do
      get :documents
      get :informal_will
      get :health
    end
  end
  resources :users, only: %i[show edit update destroy]
  # delete "users/:id", to: "users#destroy", as: "delete_user"
  get 'my_funeral', to: 'funerals#my_funeral'
  get 'my_profile', to: 'pages#my_profile'
  get '/user_profile/:id', to: 'pages#user_profile', as: 'userprofile'
  get 'about_us', to: 'pages#about_us'
  get 'loss_and_grief', to: 'pages#loss_and_grief'
  get 'forum', to: 'pages#forum'
end

app/models/funeral.rb
class Funeral < ApplicationRecord
  belongs_to :user
  has_one :funeral_flower, dependent: :destroy
  # has_many :flowers, through: :funeral_flower, dependent: :destroy
  has_one :guest, dependent: :destroy
  has_one :funeral_home, dependent: :destroy
  has_one :venue , dependent: :destroy
  validates :user, presence: true, uniqueness: true
  has_many :relatives, dependent: :destroy
  has_many_attached :documents
  has_rich_text :informal_will
  has_rich_text :health
end

app/controllers/funerals_controller.rb
class FuneralsController < ApplicationController
  before_action :everything, only: [:show, :documents, :my_funeral, :edit, :update, :destroy, :informal_will, :health]

  def show
    @active = :funeral

    @venue_markers = [{
      lat: @venue.latitude,
      lng: @venue.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {venue: @venue}),
      marker_html: render_to_string(partial: "marker", locals: {venue: @venue}),
    }] if @venue&.geocoded?
    @funeral_home_markers = [{
      lat: @funeral_home.latitude,
      lng: @funeral_home.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {funeral_home: @funeral_home}),
      marker_html: render_to_string(partial: "marker", locals: {funeral_home: @funeral_home}),
    }] if @funeral_home&.geocoded?
  end

  def documents
    @active = :documents
  end

  def informal_will
    @active = :informal_will
    @funeral = Funeral.find(params[:id])
  end

  def health
    @active = :health
    @funeral = Funeral.find(params[:id])
  end

  def my_funeral
    @funeral = Funeral.find_or_create_by(user_id: current_user.id)
    @flower = @funeral.funeral_flower
    @funeral_home = @funeral.funeral_home
    @guest = @funeral.guest
    @venue = @funeral.venue

    if @funeral.new_record?
      @funeral.save
    end
  end

  def new
    @funeral = Funeral.new
  end

  def create
    @funeral = Funeral.new(funeral_params)
    @funeral.user = current_user
    if @funeral.save
      redirect_to funeral_path(@user.funerals.first)
    else
      render :new
    end
  end

  def edit
    @funeral = Funeral.find(params[:id])
  end

  def update
    @funeral = Funeral.find(params[:id])

    if @funeral.update(funeral_params)
      if params[:funeral][:informal_will].present?
        redirect_to informal_will_funeral_path(@funeral)
      elsif params[:funeral][:documents].present?
        redirect_to documents_funeral_path(@funeral)
      elsif params[:funeral][:health].present?
        redirect_to health_funeral_path(@funeral)
      else
        redirect_to funeral_path(@funeral), notice: 'That was successful!'
      end
    else
      render :edit
    end
  end

  def destroy
    @funeral = Funeral.find(params[:id])
    @funeral.destroy
    redirect_to my_funeral_path(@funeral)
  end

  private

  def everything
    @funeral = Funeral.find(params[:id])
    @flower = @funeral.funeral_flower
    @funeral_home = @funeral.funeral_home
    @guest = @funeral.guest
    @venue = @funeral.venue
    @user = @funeral.user
  end


  def funeral_params
    params.require(:funeral).permit(:user_id, :informal_will, :health, documents: [])
  end
end

app/views/funerals/_marker.html.erb
<i class="fa-solid fa-location-dot"></i>

app/views/funerals/documents.html.erb
<% content_for :mainpage do %>

<%= render "shared/user_navbar" %>

<div class="container">
    <h1>Documents</h1>

<% if user_signed_in? && (@user == current_user || current_user.invitations(@funeral).exists?) %>


  <% if @funeral.documents.attached? %>
      <% @funeral.documents.each do |document| %>
        <div style="header">
        </div>
        <div class="card-will">
          <%#= cl_image_tag(document.key, controls: true, width: 300, height: 300, crop: :limit) %>
          <%#= link_to "Download", cl_image_path(document.key), target: :blank %>
          <%= link_to document.filename, rails_blob_url(document, disposition: 'attachment'), target: :blank %>
        </div>
      <% end %>
  <br>

    <h4>Upload more Documents</h4>
    <div class="card-will">
      <%= simple_form_for @funeral do |f| %>
      <div class="container-button-right">
      <%= f.file_field :documents, multiple: true %>
      <div class="button-right">
        <%= f.submit 'Upload', class: 'button-blue' %>
      </div>
      <% end %>
    </div>
  </div>
  <br>


  <% else %>
    <div style="header">
      <h1>Upload Documents</h1>
    </div>
    <div class="card-will">
      <%= simple_form_for @funeral do |f| %>
        <div class="container-button-right">
      <%= f.file_field :documents, multiple: true %>
        <div class="button-right">
          <%= f.submit 'Upload Will', class: 'button-blue' %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
</div>
<% else %>
  <div class="card-will">
    <p>Sorry, you are not authorized to view this page.</p>
  </div>
  <% end %>
<% end %>

app/views/funerals/health.html.erb
<% content_for :mainpage do %>

<%= render "shared/user_navbar" %>

<div class="container">
  <h1>Health</h1>
  <% if user_signed_in? && (@user == current_user || current_user.invitations(@funeral).exists?) %>
  <div class="card-will">
    <p><%= @funeral.health %></p>
  </div>

    <%= simple_form_for(@funeral) do |f| %>
      <div class="form-inputs">
        <%= f.rich_text_area :health %>
      </div>

  <br>
    <div class="form-actions">
      <%= f.button :submit, value: 'Edit' %>
    </div>
  <br>

  <% end %>
<br>
<br>

</div>
<% else %>
  <div class="card-will">
    <p>Sorry, you are not authorized to view this page.</p>
  </div>
  <% end %>
<% end %>

app/views/funerals/informal_will.html.erb
<% content_for :mainpage do %>

<%= render "shared/user_navbar" %>

<div class="container">
  <h1>Informal Will</h1>
<% if user_signed_in? && (@user == current_user || current_user.invitations(@funeral).exists?) %>
  <div class="card-will">
    <p><%= @funeral.informal_will %></p>
  </div>

    <%= simple_form_for(@funeral) do |f| %>
      <div class="form-inputs">
        <%= f.rich_text_area :informal_will %>
      </div>
      <br>

      <div class="form-actions">
        <%= f.button :submit, value: 'Edit' %>
      </div>
      <br>

    <% end %>
  <br>
  <br>
</div>
<% else %>
  <div class="card-will">
    <p>Sorry, you are not authorized to view this page.</p>
  </div>
  <% end %>
<% end %>

app/views/funerals/my_funeral.html.erb
<div class="container">
<h1> Funeral settings</h1>

<div class="button-container">
  <% if @flower.present? %>
    <%= link_to @funeral.funeral_flower.flower.name,  edit_funeral_funeral_flower_path(@funeral, @funeral.funeral_flower) %>
    <%= image_tag @funeral.flowers.first.photo %>
  <% else %>
    <%= link_to 'Add Flower', new_funeral_funeral_flower_path(@funeral) %>
  <% end %>
</div>

<div class="button-container">
  <% if @funeral_home.present? %>
    <%= link_to @funeral_home.name,  edit_funeral_funeral_home_path(@funeral, @funeral.funeral_home) %>
  <% else %>
    <%= link_to 'Add Funeral Home', new_funeral_funeral_home_path(@funeral) %>
  <% end %>
</div>

<div class="button-container">
  <% if @venue.present? %>
    <%= link_to @venue.name, edit_funeral_venue_path(@funeral, @funeral.venue) %>
  <% else %>
    <%= link_to 'Add Venue', new_funeral_venue_path(@funeral) %>
  <% end %>
</div>

<div class="button-container">
  <% if @guest.present? %>
    <%= link_to @guest.guest_count, edit_funeral_guest_path(@funeral, @funeral.guest) %>
  <% else %>
    <%= link_to 'Add Guests', new_funeral_guest_path(@funeral) %>
  <% end %>
</div>

<%= link_to "add a relative", new_funeral_relative_path(@funeral), class: "button-blue" %>

<style>
  .button-container {
    margin-top: 20px;
  }
</style>
</div>

app/views/funerals/new.html.erb
<h1> New funeral organization </h1>

app/views/funerals/show.html.erb
<% content_for :mainpage do %>
  <%= render "shared/user_navbar" %>

  <div class="container">

      <h1>Funeral Arrangements</h1>
  <% if user_signed_in? && (@user == current_user || current_user.invitations(@funeral).exists?) %>
      <div class="intern">
        <h5>Flowers</h5>
        <div class="card-big funeral normal" style="background-image: url('<%= if @funeral.funeral_flower && @funeral.funeral_flower.flower.photo.attached?
            cl_image_path(@funeral.funeral_flower.flower.photo.key)
          else
            asset_path("flowers.jpg")
          end %>'); background-size: cover; background-position: center">
          <% if @flower.present? %>
              <%= link_to @funeral.funeral_flower.flower.name, edit_funeral_funeral_flower_path(@funeral, @funeral.funeral_flower) %>
          <% else %>
            <%= link_to 'Add Flower', new_funeral_funeral_flower_path(@funeral) %>
          <% end %>
        </div>
      </div>

      <div class = "container-small">

        <div class="intern" style="max-width: 380px;">
          <h5>Funeral Home</h5>
            <% if @funeral.funeral_home.present? %>
            <p>Name: <%= link_to @funeral.funeral_home.name, edit_funeral_funeral_home_path(@funeral, @funeral.funeral_home) %></p>
            <p>Adress: <%= @funeral.funeral_home.address %></p>
            <div class="card-big-map funeral big" id="map" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @funeral_home_markers.to_json %>" >
                <%= link_to @funeral.funeral_home.name, edit_funeral_funeral_home_path(@funeral, @funeral.funeral_home) %>
            </div>
            <% else %>
            <div class="card-big-map funeral big" style="background-image: url('<%= asset_path("funeralhome_banner.jpg") %>'); background-size: cover;">
              <% if current_user == @funeral.user %>
                <%= link_to 'Add Funeral Home', new_funeral_funeral_home_path(@funeral) %>
              <% else %>
                <%= link_to 'Add Funeral Home', new_funeral_funeral_home_path(@funeral) %>
              <% end %>
            </div>
            <% end %>
        </div>

        <div class="intern" style="max-width: 380px;">
          <h5>Venue</h5>
          <% if @funeral.venue.present? %>
          <p>Name: <%= link_to @funeral.venue.name, edit_funeral_venue_path(@funeral, @funeral.venue) %></p>
          <p>Adress: <%=@funeral.venue.address%></p>
          <div class="card-big-map funeral big" id="map" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @venue_markers.to_json %>" >
              <%= link_to @funeral.venue.name, edit_funeral_venue_path(@funeral, @funeral.venue) %>
          </div>
          <% else %>

          <div class="card-big-map funeral big" style="background-image: url('<%= asset_path("venue_banner.jpg") %>'); background-size: cover;">
            <%= link_to 'Add Venue', new_funeral_venue_path(@funeral) %>
          </div>
            <% end %>
        </div>

        </div>
          <div class="intern">
            <h5>Number of Guests</h5>
            <div class="card-big funeral normal" style="background-image: url('<%= asset_path("guests_banner.png") %>'); background-size: cover;">
              <% if @funeral.guest.present? %>
                <%= link_to "Guests: " + (@funeral.guest.guest_list.match?(/\d+/) ? @funeral.guest.guest_list.scan(/\d+/).map(&:to_i).sum.to_s : @funeral.guest.guest_list.split(",").count.to_s), edit_funeral_guest_path(@funeral, @funeral.guest)  %>
              <% else %>
                <%= link_to 'Add Guests', new_funeral_guest_path(@funeral) %>
              <% end %>
          </div>
        </div>

      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="intern">
          <h5>Discuss your thoughts with friends & family</h5>
          <h2>Share to TakeCare</h2>
          <div style="button text-align: center;">
            <%= link_to "Invite", new_funeral_relative_path(@funeral), class: 'button-blue' %>
          </div>
        </div>
      <% end %>

        <br>
        <br>
    </div>
<% else %>
  <div class="card-will">
    <p>Sorry, you are not authorized to view this page.</p>
  </div>
  <% end %>

<% end %>