config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :funerals, only: %i[show new create destroy update index] do
    resources :guests, only: %i[index new show create edit update destroy]
    resources :funeral_flowers, only: %i[index show new create edit update destroy]
    resources :venues, only: %i[index new show create edit update destroy]
    resources :funeral_homes, only: %i[index show new create edit update destroy]
    resources :relatives, only: %i[new show create]
    member do
      get :documents
      get :informal_will
      get :health
    end
  end
  resources :users, only: %i[show edit update destroy]
  # delete "users/:id", to: "users#destroy", as: "delete_user"
  get 'my_funeral', to: 'funerals#my_funeral'
  get 'my_profile', to: 'pages#my_profile'
  get '/user_profile/:id', to: 'pages#user_profile', as: 'userprofile'
  get 'about_us', to: 'pages#about_us'
  get 'loss_and_grief', to: 'pages#loss_and_grief'
  get 'forum', to: 'pages#forum'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-content container text-center">
    <div class="footer-social-icons">
      <h3 class="footer-social-icons-header">Like & Follow</h3>
      <ul class="list-inline">
        <li class="list-item list-inline-item fa-2x">
          <a href="https://www.instagram.com/takecaree2023/" target="_blank" aria-label="Instagram" class="footer-social-icons-item">
            <i class="fab fa-instagram"></i>
          </a>
        </li>
        <li class="list-item list-inline-item fa-2x">
          <a href="https://www.facebook.com/lewagon/" target="_blank" aria-label="Facebook" class="footer-social-icons-item">
            <i class="fab fa-facebook"></i>
          </a>
        </li>
        <li class="list-item list-inline-item fa-2x">
          <a href="https://twitter.com/LeWagonGermany" target="_blank" aria-label="Twitter" class="footer-social-icons-item">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
      </ul>
    </div>
    <div class = "footer-p">
      <p>© 2023 Copyright: TakeCare</p>
    </div>
    <br>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="text-navbar">

      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.svg" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <% if user_signed_in? %>
          <%= link_to "My Wishes", userprofile_path(current_user.id), class: "text-navbar-child" %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "My Loved Ones", root_path, class: "text-navbar-child" %>
        <% end %>
    </div>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
              <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key,
                  crop: :fill,
                  class: "avatar dropdown-toggle",
                  id:"navbarDropdown", data: {bs_toggle: "dropdown"},
                  aria: {expanded: "false", haspopup: "true"}
                  %>
              <% else %>
                <%= image_tag('user.svg', class: "avatar dropdown-toggle", id: 'navbarDropdown', data: {bs_toggle: "dropdown"},
                  aria: {expanded: "false", haspopup: "true"}) %>
              <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= userprofile_path(current_user.id) %>">My Profile</a>
            <% if !current_user.funerals%>
              <a class="dropdown-item" href="<%= funeral_path(@current_user_funeral) %>">My Funeral</a>
            <% else %>
              <a class="dropdown-item" href="<%= health_funeral_path(current_user.funerals.first) %>">My Health</a>
              <a class="dropdown-item" href="<%= funeral_path(current_user.funerals.first) %>">My Funeral</a>
              <a class="dropdown-item" href="<%= documents_funeral_path(current_user.funerals.first) %>">My Documents</a>
              <a class="dropdown-item" href="<%= informal_will_funeral_path(current_user.funerals.first) %>">My Informal Will</a>
            <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_user_navbar.html.erb
<div class="card-user">
  <div class="user-first">
    <div class="user-name">
      <h1><%= @user.name %> <%= @user.surname %></h1>
    </div>
    <div class="user-avatar card-user-avatar-bordered">
      <% if @user.avatar.attached? %>
        <%= cl_image_tag @user.avatar.key %>
      <% else %>
        <%= image_tag("avatar.png") %>
      <% end %>
    </div>
    <div class="user-background">
      <% if @user.background_picture&.attached? %>
        <%= cl_image_tag @user.background_picture.key %>
      <% else %>
        <%= image_tag("green_leaves.jpg") %>
      <% end %>
    </div>

    <div class="user-navbar">
        <% if user_signed_in? %>
          <%= link_to "Profile", userprofile_path(@user), class: "#{'active' if @active == :relative}" %>
        <% end %>

        <% if user_signed_in? %>
        <%= link_to "Health", health_funeral_path(@funeral), class: "#{'active' if @active == :health}" %>
        <% end %>

        <% if user_signed_in? && @user.funerals.any? %>
        <%= link_to "Funeral", funeral_path(@user.funerals.first), class: "#{'active' if @active == :funeral}"  %>
        <% end %>

        <% if user_signed_in?%>
        <%= link_to "Documents", documents_funeral_path(@funeral), class: "#{'active' if @active == :documents}"%>
        <% end %>

        <% if user_signed_in? %>
        <%= link_to "Informal Will", informal_will_funeral_path(@funeral), class: "#{'active' if @active == :informal_will}"%>
        <% end %>
    </div>
  </div>